### PR TITLE
Removed the calendar activity and the button that connects with it

### PR DESCRIPTION
**Pull request by SamantaTarun**
Removed the calendar activity and the button that connects with it. As well as restructured the layout.

#7

### CODE REVIEW

**Comment by SilDijkman** [comment]
Lmfaooo my dude, why did u solve one of our TODO's?

**Comment by SamantaTarun** [comment]
I found this issue via open source site.

Please merge it. I have completed.

**Comment by SamantaTarun** [comment]
Please merge it. I want to show open source contribution.

I found this issue via goodfirstissues.com.

Although this issue was unassigned.

**Comment by FrankBosman** [comment]
Hey,
I see your branch is outdated.
and we first have to discuss your contribution after the Christmas break before we can accept it as it is a group project.
We do admire your initiative to get involved with small repositories, but we didn't think that someone would.

kind regards and hopefully your fine with this arrangement.
kind regards and of course deftige joe joe.
Frank

**Comment by SamantaTarun** [comment]
Thanks for your response.
Site name: I found this issue via goodfirstissues.com.

**Comment by FrankBosman** [comment]
Hey,
I threw it in the group, but sadly we can't accept your contribution as it is a university project and we're supposed to make it ourselves.
But I hope this doesn't discourage you from contributing to other repos.
I have already removed the good first-issue labels to make sure it won't happen again, again I'm sorry. We never expected this to happen 😅.

Have a nice rest of Christmas and the best wishes!!.
Kind regards and deftige joe joe,
Frank

**Pull request closed without merging**
